name: gunluk_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  # ğŸŒ Lokalizasyon desteÄŸi iÃ§in eklendi
    sdk: flutter
  cupertino_icons: ^1.0.8

  # GÃ¼nlÃ¼k uygulamasÄ± iÃ§in gerekli paketler
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  intl: ^0.19.0
  encrypt: ^5.0.0  # Åifreleme iÃ§in encrypt paketini ekledik

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Hive iÃ§in kod Ã¼retici
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true